# Generated by Django 3.1.2 on 2021-04-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(default=99999999)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('credit', models.IntegerField(default=0)),
                ('course_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('expertise', models.CharField(max_length=50)),
                ('max_teaching_load', models.IntegerField(default=999999999)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('strength', models.IntegerField(default=0)),
                ('courses', models.ManyToManyField(null=True, to='catalog.Course')),
            ],
        ),
    ]
