# Generated by Django 3.1.2 on 2020-10-21 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(default=99999999)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('credit', models.IntegerField(default=0)),
                ('course_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('expertise', models.CharField(max_length=50)),
                ('max_teaching_load', models.IntegerField(default=999999999)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('strength', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.course')),
                ('lecturers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.lecturer')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.studentgroup')),
            ],
        ),
    ]
